export {
    CONTRACT_VERSION,
    ExtensionAuthorizationSchema,
    ExtensionMessageSchema,
    ExtensionSyncStatusSchema,
    LocalSessionArchiveSchema,
    RecordingRequestMessageSchema,
    RecordingResponseMessageSchema,
    SignedImageUploadSchema,
    SessionSyncResponseSchema,
    SyncRequestMessageSchema,
    SyncResponseMessageSchema,
} from "@capchur/contracts";

export type {
    ActionCapture,
    CaptureActionType,
    CapturedStep,
    ClickCapture,
    ExtensionMessage,
    ExtensionAuthorization,
    ExtensionSyncStatus,
    LocalSessionArchive,
    RecordingRequestMessage,
    RecordingResponseMessage,
    RecordingSession,
    SessionSyncRequest,
    SessionSyncResponse,
    SyncRequestMessage,
    SyncResponseMessage,
} from "@capchur/contracts";