packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@esbuild-kit/core-utils>esbuild": "0.25.12"
  "firefox-profile>adm-zip": "0.6.0"
  "fx-runner>shell-quote": "1.9.0"
  "next>postcss": "8.5.25"
  "next>sharp": "0.35.3"

allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: true
  unrs-resolver: true
