import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Capchur",
  description: "How Capchur collects, uses, stores, and protects information.",
};

export default function PrivacyPage() {
  return (
    <main className="legal-page">
      <header className="legal-header">
        <Link className="shared-brand" href="/" aria-label="Capchur home">C</Link>
        <nav aria-label="Legal page navigation"><Link href="/">Home</Link><Link href="/help">Help</Link></nav>
      </header>
      <article>
        <header className="legal-title"><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p>Effective August 6, 2026</p></header>
        <section><h2>Overview</h2><p>Capchur records browser workflows that you explicitly start and turns them into editable visual guides. This policy explains how the Capchur browser extension and web application collect, use, store, and share information.</p><p>Questions and privacy requests can be sent to <a href="mailto:privacy@capchur.io">privacy@capchur.io</a>.</p></section>
        <section><h2>Information We Process</h2><h3>Account and authentication information</h3><p>We process your name, email address, workspace membership, authentication records, web sessions, and an expiring extension credential used to connect the extension to your Capchur workspace. Capchur does not collect passwords entered on recorded websites.</p><h3>Workflow and website information</h3><p>While recording is active, Capchur may process the page URL and title, supported clicks, committed input or selection actions without the entered value, form submissions, privacy-filtered element labels and geometry, viewport details, and screenshots of the visible browser tab.</p><h3>Guide and collaboration information</h3><p>We process guides, edits, image crops and redactions, comments, revisions, sharing settings, exports, and security audit events that you or your workspace create.</p><h3>Service information</h3><p>We process operational information such as request and job status, timestamps, error categories, export status, and AI token and cost totals. Diagnostic logs are designed not to contain captured payloads, screenshots, credentials, share tokens, or full private URLs.</p></section>
        <section><h2>Information Capchur Does Not Capture</h2><p>Capchur excludes password and payment-field values. Text-input and selection actions record that an action occurred, not the value entered or selected. Capchur does not record protected browser pages, native desktop applications, canvas or WebGL content semantics, closed shadow roots, or inaccessible cross-origin frames.</p></section>
        <section><h2>When Collection Happens</h2><p>The extension does not record continuously. Recording begins only when you choose to start or resume it. Site access is requested for the active HTTP or HTTPS site, and you can deny access without losing the current session. You can stop recording at any time and review or delete local steps before syncing.</p><p>The Firefox version requires Firefox 140 or later and uses Firefox&apos;s built-in data collection consent experience. Chrome and Edge display the extension&apos;s requested permissions and site-access controls through their browser interfaces.</p></section>
        <section><h2>How We Use Information</h2><ul><li>Record, review, synchronize, edit, and export workflow guides.</li><li>Provide workspace access, comments, revisions, and revocable sharing.</li><li>Authenticate users and protect workspace boundaries.</li><li>Operate, troubleshoot, secure, and improve service reliability.</li><li>Respond to support, privacy, abuse, and security requests.</li></ul><p>We do not sell personal information, use captured content for advertising, or transmit browsing information for a purpose unrelated to creating and managing Capchur guides.</p></section>
        <section><h2>Local Storage and Cloud Sync</h2><p>Recording state, steps, screenshots, review edits, and a resumable sync queue can remain in browser storage until you clear them or remove the extension&apos;s data. Cloud sync occurs after you connect an authenticated Capchur workspace. Synced data is sent over encrypted HTTPS to Capchur&apos;s production service at capchur.io.</p></section>
        <section><h2>Sharing and Service Providers</h2><p>Guides are private by default. A workspace owner can make a guide available to workspace members or create a revocable link. Anyone who has an active link can view that guide until the link is revoked.</p><p>Capchur uses restricted infrastructure providers for database, object storage, backup, email delivery, and application hosting. These providers process information only to deliver their contracted services. We may disclose information when required by law or when necessary to protect users, the service, or others.</p></section>
        <section><h2>Optional AI Processing</h2><p>AI description enhancement is off by default and runs only after a workspace owner opts in for a step. Capchur sends bounded, redacted step text to the configured AI provider. It does not send screenshots, credentials, full page content, or tools for this feature. Capchur retains usage totals rather than the AI request content; provider retention is governed by the configured provider agreement.</p></section>
        <section><h2>Retention and Deletion</h2><ul><li>Local extension sessions remain until you clear them or remove extension data.</li><li>Guides and related source content remain until a workspace owner deletes the guide.</li><li>Generated PDF and DOCX artifacts expire after 24 hours.</li><li>Web sessions last up to 7 days; extension credentials expire after 1 hour.</li><li>Encrypted production backups retain up to 30 daily recovery points and are isolated for disaster recovery.</li></ul><p>Deletion removes information from live systems. Residual backup copies age out within 30 days and are not restored except for disaster recovery.</p></section>
        <section><h2>Your Choices and Requests</h2><p>You can stop recording, deny or revoke site access, delete local sessions, remove steps before sync, revoke guide links, and delete guides you own. You may request access, correction, export, or deletion of your account information by emailing <a href="mailto:privacy@capchur.io">privacy@capchur.io</a>. We may verify your identity and workspace authority before completing a request.</p></section>
        <section><h2>Security</h2><p>Capchur uses encrypted transport, private storage, scoped authorization, expiring credentials, runtime validation, audit events, backup controls, and tested deletion procedures. No system is completely secure. Report suspected vulnerabilities to <a href="mailto:security@capchur.io">security@capchur.io</a> without including captured private content or credentials in the initial report.</p></section>
        <section><h2>Children</h2><p>Capchur is a workplace productivity service and is not directed to children. We do not knowingly collect personal information from children.</p></section>
        <section><h2>Changes to This Policy</h2><p>We may update this policy when the product, providers, or legal requirements change. Material changes will update the effective date and will be communicated through the service or browser-store listing where appropriate.</p></section>
        <footer><p>Privacy: <a href="mailto:privacy@capchur.io">privacy@capchur.io</a></p><p>Support: <a href="mailto:support@capchur.io">support@capchur.io</a></p></footer>
      </article>
    </main>
  );
}